# NumPy - Array Creation and Manipulation



In [ ]:
import numpy as np

---
## Exercise 1 - Creating a 1D Array (0 to 9)

`np.arange(n)` generates an integer sequence from 0 up to (but not including) `n`.
It is the NumPy equivalent of Python's built-in `range()`, but returns an `ndarray` directly.

In [ ]:
arr1 = np.arange(10)

print('Array:', arr1)
print('Shape:', arr1.shape)
print('dtype:', arr1.dtype)

**Expected output**
```
array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
```

---
## Exercise 2 - Type Conversion

`np.array(..., dtype=int)` converts each element while building the array.
Alternatively, `.astype(int)` performs an explicit cast on an existing array.
Both truncate (do not round) the decimal part: `3.14 -> 3`, `2.17 -> 2`.

In [ ]:
python_list = [3.14, 2.17, 0, 1, 2]

# Method 1: specify dtype at creation time
arr2 = np.array(python_list, dtype=int)

# Method 2: convert after creation (equivalent result)
arr2_alt = np.array(python_list).astype(int)

print('Method 1 (dtype=int):  ', arr2)
print('Method 2 (.astype):    ', arr2_alt)
print('dtype:', arr2.dtype)

**Expected output**
```
array([3, 2, 0, 1, 2])
```

---
## Exercise 3 - 3x3 Multi-Dimensional Array (1 to 9)

`np.arange(1, 10)` generates integers from 1 to 9 inclusive.
`.reshape(3, 3)` rearranges the flat sequence into a 3-row, 3-column matrix without copying data.
The total number of elements must match: `3 × 3 = 9`.

In [ ]:
arr3 = np.arange(1, 10).reshape(3, 3)

print('Array:')
print(arr3)
print('Shape:', arr3.shape)
print('Number of dimensions:', arr3.ndim)

**Expected output**
```
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])
```

---
## Exercise 4 - 2D Array with Random Numbers (shape 4×5)

`np.random.rand(rows, cols)` draws samples from a uniform distribution over [0, 1).
Setting a random seed with `np.random.seed()` makes the output reproducible.

In [ ]:
np.random.seed(42)          # seed for reproducibility
arr4 = np.random.rand(4, 5)

print('Array (rounded for display):')
print(np.round(arr4, 2))
print('Shape:', arr4.shape)
print('dtype:', arr4.dtype)

**Expected output** (values vary with seed)
```
array([[0.37, 0.95, 0.73, 0.60, 0.16],
       [0.16, 0.06, 0.87, 0.60, 0.71],
       [0.02, 0.97, 0.83, 0.21, 0.18],
       [0.18, 0.30, 0.52, 0.43, 0.29]])
```

---
## Exercise 5 - Array Indexing (select the second row)

NumPy uses **zero-based** indexing: the second row is at index `1`.
`array[1]` is shorthand for `array[1, :]` — select all columns of row 1.

In [ ]:
arr5 = np.array([
    [21, 22, 23, 22, 22],
    [20, 21, 22, 23, 24],
    [21, 22, 23, 22, 22]
])

second_row = arr5[1]          # equivalent to arr5[1, :]

print('Full array:')
print(arr5)
print()
print('Second row (index 1):', second_row)

**Expected output**
```
array([20, 21, 22, 23, 24])
```

---
## Exercise 6 - Reversing a 1D Array

The slicing syntax `[::-1]` means: start at the end, step backwards by 1.
This returns a **view** (no data is copied), making it very memory-efficient.

In [ ]:
arr6 = np.arange(10)          # [0, 1, 2, ..., 9]

arr6_reversed = arr6[::-1]

print('Original array: ', arr6)
print('Reversed array: ', arr6_reversed)

**Expected output**
```
array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])
```

---
## Exercise 7 - 4×4 Identity Matrix

`np.eye(n)` creates an `n×n` matrix with 1s on the main diagonal and 0s elsewhere.
Identity matrices are fundamental in linear algebra: multiplying any matrix by the identity returns the original matrix unchanged.

In [ ]:
identity = np.eye(4)

print('4x4 Identity Matrix:')
print(identity)
print('Shape:', identity.shape)
print('dtype:', identity.dtype)

**Expected output**
```
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])
```

---
## Exercise 8 - Aggregate Functions (sum and average)

`np.sum()` and `np.mean()` are vectorised operations executed in compiled C code,
making them orders of magnitude faster than equivalent Python loops on large arrays.
The array `[0, 1, ..., 9]` has sum = 45 and mean = 45/10 = 4.5.

In [ ]:
arr8 = np.arange(10)          # [0, 1, 2, ..., 9]

total   = np.sum(arr8)
average = np.mean(arr8)

print(f'Array:   {arr8}')
print(f'Sum:     {total}')
print(f'Average: {average}')

# Additional aggregate functions for reference
print(f'Min:     {np.min(arr8)}')
print(f'Max:     {np.max(arr8)}')
print(f'Std Dev: {np.std(arr8):.4f}')

**Expected output**
```
Sum: 45, Average: 4.5
```

---
## Exercise 9 - Create and Reshape an Array (1 to 20 → 4×5)

`np.arange(1, 21)` generates integers from 1 to 20 inclusive (20 elements).
`.reshape(4, 5)` rearranges them into 4 rows and 5 columns.
Rule: `rows × cols` must equal the total number of elements — here `4 × 5 = 20`.

In [ ]:
arr9 = np.arange(1, 21).reshape(4, 5)

print('Reshaped array (4x5):')
print(arr9)
print('Shape:', arr9.shape)

# Flatten back to 1D for reference
print('\nFlattened back to 1D:', arr9.flatten())

**Expected output**
```
array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])
```

---
## Exercise 10 - Conditional Selection (extract odd numbers)

**Boolean masking** is one of NumPy's most powerful features:
1. `arr % 2 != 0` creates a boolean array of the same shape (`True` where the condition holds).
2. Passing that boolean array as an index selects only the elements where the mask is `True`.

This is far more readable and faster than a Python list comprehension.

**Expected output**
```
array([1, 3, 5, 7, 9])
```

In [ ]:
arr10 = np.arange(10)         # [0, 1, 2, ..., 9]

# Step 1: create the boolean mask
odd_mask = arr10 % 2 != 0
print('Boolean mask:', odd_mask)

# Step 2: apply the mask
odd_numbers = arr10[odd_mask]
print('Odd numbers: ', odd_numbers)

# One-liner equivalent
print('One-liner:   ', arr10[arr10 % 2 != 0])